(function (root) {
  root.CONECTAZ_COURSES = {
    ux: {
      title: 'Fundamentos de UX e design de produto', category: 'UX & produto', description: 'Entenda as necessidades das pessoas, transforme problemas em oportunidades e teste soluções com confiança.', instructor: 'Conteúdo demonstrativo', initials: 'CZ', level: 'Iniciante', duration: '12 horas', image: 'ux.svg', pdf: 'guia-ux-produto.pdf', quote: 'O bom design começa com curiosidade e melhora com escuta.', challenge: 'Escolha uma tarefa cotidiana e faça três conversas curtas para descobrir onde as pessoas encontram dificuldade.', checklist: ['Escrevi o problema do ponto de vista da pessoa usuária', 'Registrei evidências antes de propor a solução', 'Criei um protótipo para responder a uma hipótese', 'Observei três pessoas usando o protótipo'], modules: [
        ['Pesquisa e descoberta', [['Conversas que revelam necessidades', 'Como preparar entrevistas curtas e abertas para entender contexto, motivação e comportamento.'], ['Mapeando a jornada atual', 'Organize etapas, dúvidas e pontos de atrito sem presumir a solução antes da hora.']]],
        ['Estrutura e prototipação', [['Do problema à hipótese', 'Escreva uma hipótese verificável e escolha o recorte de produto que merece ser testado.'], ['Prototipar para pensar', 'Use fluxos simples e baixa fidelidade para tornar ideias conversáveis.']]],
        ['Teste e evolução', [['Testes de usabilidade leves', 'Planeje tarefas, convide participantes e observe sem conduzir as respostas.'], ['Decisões com evidências', 'Organize aprendizados, priorize oportunidades e comunique o próximo experimento.']]]],
    },
    dados: {
      title: 'Dados na prática: do zero à análise', category: 'Tecnologia & dados', description: 'Aprenda a formular perguntas, organizar dados e apresentar descobertas úteis para decisões do dia a dia.', instructor: 'Conteúdo demonstrativo', initials: 'CZ', level: 'Iniciante', duration: '16 horas', image: 'data.svg', pdf: 'caderno-dados-pratica.pdf', quote: 'Uma boa pergunta é o primeiro passo de uma boa análise.', challenge: 'Use uma planilha pública ou fictícia para responder uma pergunta de negócio e escrever uma recomendação baseada em evidências.', checklist: ['Defini a decisão antes de analisar', 'Conferi formato, unidades e valores ausentes', 'Escolhi um gráfico que responde à pergunta', 'Separei observações de conclusões'], modules: [
        ['Perguntas e qualidade dos dados', [['Da decisão à pergunta analítica', 'Converta uma dúvida ampla em uma pergunta que possa orientar uma ação concreta.'], ['Limpeza e organização', 'Confira tipos, duplicidades, vazios e consistência antes de calcular qualquer coisa.']]],
        ['Análise e visualização', [['Resumo estatístico sem mistério', 'Use contagens, médias e comparações com atenção ao contexto e às unidades.'], ['Gráficos que explicam', 'Escolha uma visualização pela comparação que deseja tornar fácil de perceber.']]],
        ['Comunicação de resultados', [['Da descoberta à recomendação', 'Construa uma narrativa curta que conecte pergunta, evidência, recomendação e limite.'], ['Apresentação para decisão', 'Prepare um resumo executivo e antecipe dúvidas sem esconder incertezas.']]]],
    },
    comunicacao: {
      title: 'Comunicação para times que crescem', category: 'Carreira & negócios', description: 'Conduza alinhamentos melhores, escute com intenção e transforme conversas em decisões claras.', instructor: 'Conteúdo demonstrativo', initials: 'CZ', level: 'Todos os níveis', duration: '9 horas', image: 'communication.svg', pdf: 'guia-comunicacao-times.pdf', quote: 'Clareza é uma forma de cuidado com o tempo de todo mundo.', challenge: 'Escolha uma conversa de alinhamento real. Prepare contexto e pedido, escute a outra pessoa e registre uma decisão compartilhada.', checklist: ['Expliquei o contexto e o impacto', 'Fiz um pedido específico e respeitoso', 'Confirmei o que entendi antes de responder', 'Registrei responsáveis e próximos passos'], modules: [
        ['Clareza e escuta', [['Contexto que aproxima', 'Apresente cenário, impacto e objetivo para que a conversa comece com entendimento comum.'], ['Escuta ativa no trabalho', 'Use perguntas abertas e reformulação para checar o que foi entendido.']]],
        ['Alinhamentos e feedback', [['Feedback orientado à ação', 'Descreva situações observáveis, impacto e uma expectativa de mudança possível.'], ['Conversas difíceis com respeito', 'Prepare fatos, cuide do momento e mantenha a conversa focada em acordos.']]],
        ['Reuniões e decisões', [['Reuniões que chegam a algum lugar', 'Defina propósito, participantes essenciais e uma decisão que precisa sair da conversa.'], ['Acordos que viram ação', 'Feche com responsáveis, prazos, registro e um modo simples de acompanhar.']]]],
    },
    ia: {
      title: 'Introdução à inteligência artificial', category: 'Tecnologia & dados', description: 'Conheça usos cotidianos de IA, aprenda a escrever boas instruções e avalie resultados com responsabilidade.', instructor: 'Conteúdo demonstrativo', initials: 'CZ', level: 'Iniciante', duration: '10 horas', image: 'ai.svg', pdf: 'guia-inteligencia-artificial.pdf', quote: 'Use a tecnologia para ampliar sua capacidade de pensar, não para deixar de pensar.', challenge: 'Escolha uma tarefa repetitiva, teste uma instrução em uma ferramenta de IA e revise cada afirmação com fontes confiáveis.', checklist: ['Escolhi um problema adequado à ferramenta', 'Informei contexto, público e formato', 'Verifiquei afirmações importantes', 'Protegi dados pessoais e confidenciais'], modules: [
        ['Entendendo inteligência artificial', [['O que a IA pode e não pode fazer', 'Diferencie automação, modelos de linguagem e respostas geradas por probabilidade.'], ['Exemplos de uso no trabalho', 'Encontre tarefas de apoio sem transferir decisões sensíveis ou dados privados.']]],
        ['Instruções e experimentação', [['Como escrever bons prompts', 'Combine papel, objetivo, contexto, restrições e formato para diminuir ambiguidades.'], ['Refinar e comparar respostas', 'Mude uma variável por vez e avalie os resultados com critérios claros.']]],
        ['Verificação e responsabilidade', [['Checagem de fatos e vieses', 'Verifique informações, procure omissões e reconheça vieses e limitações do modelo.'], ['Uso seguro e ético', 'Proteja dados, respeite direitos de uso e mantenha supervisão humana adequada.']]]],
    },
    portfolio: {
      title: 'Portfólio profissional com propósito', category: 'UX & produto', description: 'Apresente seu trabalho com contexto, autoria e evidências para que outras pessoas entendam o valor das suas decisões.', instructor: 'Conteúdo demonstrativo', initials: 'CZ', level: 'Intermediário', duration: '8 horas', image: 'portfolio.svg', pdf: 'roteiro-portfolio-profissional.pdf', quote: 'Seu processo também faz parte do que você tem a oferecer.', challenge: 'Escolha um projeto e prepare um estudo de caso curto que outra pessoa consiga entender em dois minutos.', checklist: ['Expliquei meu papel e o trabalho do time', 'Apresentei contexto e restrições', 'Conectei decisões a evidências', 'Mostrei resultados sem exagerar minha contribuição'], modules: [
        ['Posicionamento e seleção', [['O que seu portfólio precisa mostrar', 'Defina competências e públicos para selecionar trabalhos que contam uma história coerente.'], ['Escolhendo projetos com intenção', 'Compare projetos pela variedade de habilidades e pelo que ensinam a quem avalia.']]],
        ['Estudos de caso', [['Contexto, problema e papel', 'Escreva uma abertura simples que situe desafio, objetivo, equipe e sua responsabilidade.'], ['Processo e decisões', 'Mostre opções, critérios e evidências sem transformar o estudo de caso em um diário.']]],
        ['Apresentação e revisão', [['Resultados e aprendizados', 'Descreva impacto verificável e as perguntas que você levaria para uma próxima versão.'], ['Portfólio acessível e claro', 'Revise leitura, navegação, contraste e instruções para contato profissional.']]]],
    },
    produtividade: {
      title: 'Organização e produtividade no trabalho', category: 'Carreira & negócios', description: 'Organize prioridades com intenção, proteja tempo para o que importa e feche o dia sabendo o próximo passo.', instructor: 'Conteúdo demonstrativo', initials: 'CZ', level: 'Todos os níveis', duration: '7 horas', image: 'productivity.svg', pdf: 'planner-produtividade-trabalho.pdf', quote: 'Progresso sustentável nasce de prioridades claras e pausas possíveis.', challenge: 'Planeje um dia realista com três resultados importantes, blocos de foco e espaço para imprevistos.', checklist: ['Transformei pendências em próximas ações', 'Escolhi prioridades pelo impacto e prazo', 'Limitei tarefas em andamento', 'Reservei tempo para pausas e imprevistos'], modules: [
        ['Visibilidade e rotina', [['Tire tarefas da cabeça', 'Reúna compromissos em um sistema único e transforme assuntos vagos em ações observáveis.'], ['Revise sua semana', 'Identifique compromissos fixos, pendências e pontos de sobrecarga antes de planejar.']]],
        ['Prioridades e foco', [['Decidir o que vem primeiro', 'Compare urgência, impacto e dependências para negociar o trabalho em andamento.'], ['Blocos de foco que cabem na rotina', 'Agrupe tarefas, planeje pausas e proteja períodos realistas de concentração.']]],
        ['Ritmo sustentável', [['Interrupções e limites', 'Prepare acordos para interrupções e aprenda a renegociar quando novas demandas aparecem.'], ['Fechamento e próximo passo', 'Revise avanços sem culpa e deixe a primeira ação do dia seguinte pronta.']]]],
    },
  };
})(typeof window !== 'undefined' ? window : globalThis);
